[package]
name = "easy-sockets"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
bincode = "1.3.3"
lazy_static = "1.5.0"
serde = {version="1.0.210", features=["derive"]}
tokio = {version="1.40.0", features=["full"]}
